name: CI/CD Pipeline

on:
  push:
    branches:
      - main  # Change to your default branch if needed
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Build Docker image
      run: |
        docker build -t local-web-app .

    - name: Run Docker container
      run: |
        docker run -d -p 5000:5000 --name web-app local-web-app

    - name: Wait for the app to be available
      run: |
        sleep 10  # Wait for a few seconds to allow the app to start
        curl -f http://localhost:5000 || exit 1

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
    - name: Set up SSH key and permissions
      env:
        SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
        HOST: ${{ secrets.HOST }}
        USER: ${{ secrets.USER }}
      run: |
        echo "$SSH_PRIVATE_KEY" > private_key
        chmod 600 private_key

    - name: Deploy application to the server
      env:
        SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
        HOST: ${{ secrets.HOST }}
        USER: ${{ secrets.USER }}
      run: |
        echo "$SSH_PRIVATE_KEY" > private_key
        chmod 600 private_key
        ssh -o StrictHostKeyChecking=no -i private_key -tt $USER@$HOST << 'EOF'
          # Ensure Docker container cleanup if an old container exists
          docker stop crud-api || true
          docker rm crud-api || true
          
          # Navigate to app directory and rebuild
          cd /home/test
          docker build -t crud-api .
          docker run -d -p 5000:5000 --name crud-api crud-api:latest
        EOF
